model_name:  Linzwcs/Llama-AFT-On-Policy # path to AFT model

generation_params:
    temperature: 0.7
    top_p: 0.95
    max_tokens: 4096
    n: 5
    final_layer_temperature: 0.7
    final_layer_top_p: 1

vllm_seed: 2025

num_aggregation: 2  # Number of aggregation layers, excluding the final layer
