model_name:  /mnt/petrelfs/share_data/harold/llama_onp # path to AFT model

proposal_params:
    temperature: 0.7
    top_p: 0.95
    max_tokens: 4096
    n: 5

aggregation_params:
    temperature: 0.7
    top_p: 0.95
    max_tokens: 4096
    n: 5

vllm_seed: 2025

num_aggregation: 2  # Number of aggregation layers, excluding the final layer
