model_name: /mnt/petrelfs/share_data/harold/llama_onp

proposal_params:
    temperature: 0.7
    top_p: 0.95
    max_tokens: 4096
    n: 5

aggregation_params:
    temperature: 0.7
    top_p: 0.95
    max_tokens: 4096
    n: 5

vllm_seed: 2019

hidden_layer: 0  # Number of aggregation layers, excluding the final layer
final_aggregation: True # Indicates whether this is the final aggregation step
